// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skolaris.Data;

#nullable disable

namespace Skolaris.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501121151_AddNoteEvaluationFields")]
    partial class AddNoteEvaluationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Skolaris.Models.Absence", b =>
                {
                    b.Property<int>("IdAbsence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbsence"));

                    b.Property<DateTime>("DateAbsence")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCoursOffert")
                        .HasColumnType("int");

                    b.Property<int>("IdEleve")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAbsence");

                    b.HasIndex("IdCoursOffert");

                    b.HasIndex("IdEleve");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("Skolaris.Models.AnneeScolaire", b =>
                {
                    b.Property<int>("IdAnnee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnnee"));

                    b.Property<int>("IdEcole")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAnnee");

                    b.HasIndex("IdEcole");

                    b.ToTable("AnneesScolaires");
                });

            modelBuilder.Entity("Skolaris.Models.Bulletin", b =>
                {
                    b.Property<int>("IdBulletin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBulletin"));

                    b.Property<int>("IdEleve")
                        .HasColumnType("int");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<string>("Mention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MoyenneGeneral")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("IdBulletin");

                    b.HasIndex("IdEleve");

                    b.HasIndex("IdSession");

                    b.ToTable("Bulletins");
                });

            modelBuilder.Entity("Skolaris.Models.Conversation", b =>
                {
                    b.Property<int>("IdConversation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConversation"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sujet")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConversation");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Skolaris.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("IdConversation")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdhesion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdConversation", "IdUtilisateur");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("Skolaris.Models.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCours"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("int");

                    b.Property<int>("IdProgramme")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdCours");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdProgramme");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("Skolaris.Models.CoursOffert", b =>
                {
                    b.Property<int>("IdCoursOffert")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoursOffert"));

                    b.Property<int>("IdCours")
                        .HasColumnType("int");

                    b.Property<int?>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdGroupe")
                        .HasColumnType("int");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<string>("ModeEnseignement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCoursOffert");

                    b.HasIndex("IdCours");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdGroupe");

                    b.HasIndex("IdSession");

                    b.ToTable("CoursOfferts");
                });

            modelBuilder.Entity("Skolaris.Models.DetailBulletin", b =>
                {
                    b.Property<int>("IdDetailBulletin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetailBulletin"));

                    b.Property<int>("IdBulletin")
                        .HasColumnType("int");

                    b.Property<int>("IdCoursOffert")
                        .HasColumnType("int");

                    b.Property<int>("IdNote")
                        .HasColumnType("int");

                    b.HasKey("IdDetailBulletin");

                    b.HasIndex("IdBulletin");

                    b.HasIndex("IdCoursOffert");

                    b.HasIndex("IdNote");

                    b.ToTable("DetailBulletins");
                });

            modelBuilder.Entity("Skolaris.Models.Ecole", b =>
                {
                    b.Property<int>("IdEcole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEcole"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEcole");

                    b.ToTable("Ecoles");
                });

            modelBuilder.Entity("Skolaris.Models.Eleve", b =>
                {
                    b.Property<int>("IdEleve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEleve"));

                    b.Property<int>("IdGroupe")
                        .HasColumnType("int");

                    b.Property<int>("IdNiveau")
                        .HasColumnType("int");

                    b.Property<int>("IdProgramme")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEleve");

                    b.HasIndex("IdGroupe");

                    b.HasIndex("IdNiveau");

                    b.HasIndex("IdProgramme");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Eleves");
                });

            modelBuilder.Entity("Skolaris.Models.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEmploi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmploi"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("time");

                    b.Property<int>("IdCoursOffert")
                        .HasColumnType("int");

                    b.Property<string>("JourSemaine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmploi");

                    b.HasIndex("IdCoursOffert");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("Skolaris.Models.Enseignant", b =>
                {
                    b.Property<int>("IdEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnseignant"));

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdEnseignant");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Enseignants");
                });

            modelBuilder.Entity("Skolaris.Models.Groupe", b =>
                {
                    b.Property<int>("IdGroupe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroupe"));

                    b.Property<int>("IdProgramme")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGroupe");

                    b.HasIndex("IdProgramme");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("Skolaris.Models.Inscription", b =>
                {
                    b.Property<int>("IdInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscription"));

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCoursOffert")
                        .HasColumnType("int");

                    b.Property<int>("IdEleve")
                        .HasColumnType("int");

                    b.HasKey("IdInscription");

                    b.HasIndex("IdCoursOffert");

                    b.HasIndex("IdEleve");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("Skolaris.Models.JustificationAbsence", b =>
                {
                    b.Property<int>("IdJustification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdJustification"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdAbsence")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdJustification");

                    b.HasIndex("IdAbsence")
                        .IsUnique();

                    b.ToTable("JustificationsAbsence");
                });

            modelBuilder.Entity("Skolaris.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("Contenu")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConversation")
                        .HasColumnType("int");

                    b.Property<int>("IdExpediteur")
                        .HasColumnType("int");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdConversation");

                    b.HasIndex("IdExpediteur");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Skolaris.Models.MessageUtilisateur", b =>
                {
                    b.Property<int>("IdMessageUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMessageUtilisateur"));

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLu")
                        .HasColumnType("bit");

                    b.Property<int>("IdDestinataire")
                        .HasColumnType("int");

                    b.Property<int>("IdMessage")
                        .HasColumnType("int");

                    b.HasKey("IdMessageUtilisateur");

                    b.HasIndex("IdMessage");

                    b.ToTable("MessageUtilisateurs");
                });

            modelBuilder.Entity("Skolaris.Models.Niveau", b =>
                {
                    b.Property<int>("IdNiveau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNiveau"));

                    b.Property<int>("IdProgramme")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNiveau");

                    b.HasIndex("IdProgramme");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("Skolaris.Models.Note", b =>
                {
                    b.Property<int>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNote"));

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdCoursOffert")
                        .HasColumnType("int");

                    b.Property<int>("IdEleve")
                        .HasColumnType("int");

                    b.Property<decimal>("Ponderation")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("IdNote");

                    b.HasIndex("IdCoursOffert");

                    b.HasIndex("IdEleve");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Skolaris.Models.PaiementEleve", b =>
                {
                    b.Property<int>("IdPaiementEleve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaiementEleve"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEleve")
                        .HasColumnType("int");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaiementEleve");

                    b.HasIndex("IdEleve");

                    b.HasIndex("IdSession");

                    b.ToTable("PaiementsEleves");
                });

            modelBuilder.Entity("Skolaris.Models.PaiementEnseignant", b =>
                {
                    b.Property<int>("IdPaiementEnseignant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaiementEnseignant"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HeuresTravaillees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<int>("IdTaux")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPaiementEnseignant");

                    b.HasIndex("IdEnseignant");

                    b.HasIndex("IdSession");

                    b.HasIndex("IdTaux");

                    b.ToTable("PaiementsEnseignants");
                });

            modelBuilder.Entity("Skolaris.Models.Programme", b =>
                {
                    b.Property<int>("IdProgramme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgramme"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdProgramme");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("Skolaris.Models.Session", b =>
                {
                    b.Property<int>("IdSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSession"));

                    b.Property<int>("IdAnnee")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSession");

                    b.HasIndex("IdAnnee");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Skolaris.Models.TauxHoraireEnseignant", b =>
                {
                    b.Property<int>("IdTaux")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaux"));

                    b.Property<DateTime>("DateEffet")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEnseignant")
                        .HasColumnType("int");

                    b.Property<decimal>("TauxHoraire")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("IdTaux");

                    b.HasIndex("IdEnseignant");

                    b.ToTable("TauxHorairesEnseignants");
                });

            modelBuilder.Entity("Skolaris.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Skolaris.Models.Absence", b =>
                {
                    b.HasOne("Skolaris.Models.CoursOffert", "CoursOffert")
                        .WithMany("Absences")
                        .HasForeignKey("IdCoursOffert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Eleve", "Eleve")
                        .WithMany("Absences")
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursOffert");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("Skolaris.Models.AnneeScolaire", b =>
                {
                    b.HasOne("Skolaris.Models.Ecole", "Ecole")
                        .WithMany("AnneesScolaires")
                        .HasForeignKey("IdEcole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("Skolaris.Models.Bulletin", b =>
                {
                    b.HasOne("Skolaris.Models.Eleve", "Eleve")
                        .WithMany("Bulletins")
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Session", "Session")
                        .WithMany("Bulletins")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Skolaris.Models.ConversationParticipant", b =>
                {
                    b.HasOne("Skolaris.Models.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Utilisateur", "Utilisateur")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Skolaris.Models.Cours", b =>
                {
                    b.HasOne("Skolaris.Models.Niveau", "Niveau")
                        .WithMany("Cours")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Programme", "Programme")
                        .WithMany("Cours")
                        .HasForeignKey("IdProgramme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveau");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("Skolaris.Models.CoursOffert", b =>
                {
                    b.HasOne("Skolaris.Models.Cours", "Cours")
                        .WithMany("CoursOfferts")
                        .HasForeignKey("IdCours")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Enseignant", "Enseignant")
                        .WithMany("CoursOfferts")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Skolaris.Models.Groupe", "Groupe")
                        .WithMany("CoursOfferts")
                        .HasForeignKey("IdGroupe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Session", "Session")
                        .WithMany("CoursOfferts")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Enseignant");

                    b.Navigation("Groupe");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Skolaris.Models.DetailBulletin", b =>
                {
                    b.HasOne("Skolaris.Models.Bulletin", "Bulletin")
                        .WithMany("DetailBulletins")
                        .HasForeignKey("IdBulletin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.CoursOffert", "CoursOffert")
                        .WithMany("DetailBulletins")
                        .HasForeignKey("IdCoursOffert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Note", "Note")
                        .WithMany("DetailBulletins")
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bulletin");

                    b.Navigation("CoursOffert");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Skolaris.Models.Eleve", b =>
                {
                    b.HasOne("Skolaris.Models.Groupe", "Groupe")
                        .WithMany("Eleves")
                        .HasForeignKey("IdGroupe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Niveau", "Niveau")
                        .WithMany("Eleves")
                        .HasForeignKey("IdNiveau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Programme", "Programme")
                        .WithMany("Eleves")
                        .HasForeignKey("IdProgramme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Utilisateur", "Utilisateur")
                        .WithOne("Eleve")
                        .HasForeignKey("Skolaris.Models.Eleve", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Niveau");

                    b.Navigation("Programme");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Skolaris.Models.EmploiDuTemps", b =>
                {
                    b.HasOne("Skolaris.Models.CoursOffert", "CoursOffert")
                        .WithMany("EmploisDuTemps")
                        .HasForeignKey("IdCoursOffert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursOffert");
                });

            modelBuilder.Entity("Skolaris.Models.Enseignant", b =>
                {
                    b.HasOne("Skolaris.Models.Utilisateur", "Utilisateur")
                        .WithOne("Enseignant")
                        .HasForeignKey("Skolaris.Models.Enseignant", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Skolaris.Models.Groupe", b =>
                {
                    b.HasOne("Skolaris.Models.Programme", "Programme")
                        .WithMany("Groupes")
                        .HasForeignKey("IdProgramme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("Skolaris.Models.Inscription", b =>
                {
                    b.HasOne("Skolaris.Models.CoursOffert", "CoursOffert")
                        .WithMany("Inscriptions")
                        .HasForeignKey("IdCoursOffert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Eleve", "Eleve")
                        .WithMany("Inscriptions")
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursOffert");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("Skolaris.Models.JustificationAbsence", b =>
                {
                    b.HasOne("Skolaris.Models.Absence", "Absence")
                        .WithOne("Justification")
                        .HasForeignKey("Skolaris.Models.JustificationAbsence", "IdAbsence")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Absence");
                });

            modelBuilder.Entity("Skolaris.Models.Message", b =>
                {
                    b.HasOne("Skolaris.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("IdConversation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Utilisateur", "Expediteur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("IdExpediteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Expediteur");
                });

            modelBuilder.Entity("Skolaris.Models.MessageUtilisateur", b =>
                {
                    b.HasOne("Skolaris.Models.Message", "Message")
                        .WithMany("MessageUtilisateurs")
                        .HasForeignKey("IdMessage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Skolaris.Models.Niveau", b =>
                {
                    b.HasOne("Skolaris.Models.Programme", "Programme")
                        .WithMany("Niveaux")
                        .HasForeignKey("IdProgramme")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("Skolaris.Models.Note", b =>
                {
                    b.HasOne("Skolaris.Models.CoursOffert", "CoursOffert")
                        .WithMany("Notes")
                        .HasForeignKey("IdCoursOffert")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Eleve", "Eleve")
                        .WithMany("Notes")
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoursOffert");

                    b.Navigation("Eleve");
                });

            modelBuilder.Entity("Skolaris.Models.PaiementEleve", b =>
                {
                    b.HasOne("Skolaris.Models.Eleve", "Eleve")
                        .WithMany("Paiements")
                        .HasForeignKey("IdEleve")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Session", "Session")
                        .WithMany("PaiementsEleves")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eleve");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Skolaris.Models.PaiementEnseignant", b =>
                {
                    b.HasOne("Skolaris.Models.Enseignant", "Enseignant")
                        .WithMany("Paiements")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.Session", "Session")
                        .WithMany("PaiementsEnseignants")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skolaris.Models.TauxHoraireEnseignant", "TauxHoraire")
                        .WithMany("Paiements")
                        .HasForeignKey("IdTaux")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enseignant");

                    b.Navigation("Session");

                    b.Navigation("TauxHoraire");
                });

            modelBuilder.Entity("Skolaris.Models.Session", b =>
                {
                    b.HasOne("Skolaris.Models.AnneeScolaire", "AnneeScolaire")
                        .WithMany("Sessions")
                        .HasForeignKey("IdAnnee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnneeScolaire");
                });

            modelBuilder.Entity("Skolaris.Models.TauxHoraireEnseignant", b =>
                {
                    b.HasOne("Skolaris.Models.Enseignant", "Enseignant")
                        .WithMany("TauxHoraires")
                        .HasForeignKey("IdEnseignant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("Skolaris.Models.Absence", b =>
                {
                    b.Navigation("Justification");
                });

            modelBuilder.Entity("Skolaris.Models.AnneeScolaire", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Skolaris.Models.Bulletin", b =>
                {
                    b.Navigation("DetailBulletins");
                });

            modelBuilder.Entity("Skolaris.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Skolaris.Models.Cours", b =>
                {
                    b.Navigation("CoursOfferts");
                });

            modelBuilder.Entity("Skolaris.Models.CoursOffert", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("DetailBulletins");

                    b.Navigation("EmploisDuTemps");

                    b.Navigation("Inscriptions");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Skolaris.Models.Ecole", b =>
                {
                    b.Navigation("AnneesScolaires");
                });

            modelBuilder.Entity("Skolaris.Models.Eleve", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Bulletins");

                    b.Navigation("Inscriptions");

                    b.Navigation("Notes");

                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("Skolaris.Models.Enseignant", b =>
                {
                    b.Navigation("CoursOfferts");

                    b.Navigation("Paiements");

                    b.Navigation("TauxHoraires");
                });

            modelBuilder.Entity("Skolaris.Models.Groupe", b =>
                {
                    b.Navigation("CoursOfferts");

                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("Skolaris.Models.Message", b =>
                {
                    b.Navigation("MessageUtilisateurs");
                });

            modelBuilder.Entity("Skolaris.Models.Niveau", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Eleves");
                });

            modelBuilder.Entity("Skolaris.Models.Note", b =>
                {
                    b.Navigation("DetailBulletins");
                });

            modelBuilder.Entity("Skolaris.Models.Programme", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Eleves");

                    b.Navigation("Groupes");

                    b.Navigation("Niveaux");
                });

            modelBuilder.Entity("Skolaris.Models.Session", b =>
                {
                    b.Navigation("Bulletins");

                    b.Navigation("CoursOfferts");

                    b.Navigation("PaiementsEleves");

                    b.Navigation("PaiementsEnseignants");
                });

            modelBuilder.Entity("Skolaris.Models.TauxHoraireEnseignant", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("Skolaris.Models.Utilisateur", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Eleve");

                    b.Navigation("Enseignant");

                    b.Navigation("MessagesEnvoyes");
                });
#pragma warning restore 612, 618
        }
    }
}
